# Generated by Django 2.2.7 on 2020-01-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orienters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPersonAspectDescriptionFemale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence', models.IntegerField(default=0)),
                ('archetype', models.IntegerField(default=0)),
                ('aspect', models.IntegerField(default=0)),
                ('image', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('title_1', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('title_2', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('text_1', models.TextField(blank=True, default=None, null=True)),
                ('text_2', models.TextField(blank=True, default=None, null=True)),
                ('text_3', models.TextField(blank=True, default=None, null=True)),
                ('text_4', models.TextField(blank=True, default=None, null=True)),
                ('text_5', models.TextField(blank=True, default=None, null=True)),
                ('text_6', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'person_person_aspect_descriptions_female',
            },
        ),
        migrations.CreateModel(
            name='PersonPersonAspectDescriptionMale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence', models.IntegerField(default=0)),
                ('archetype', models.IntegerField(default=0)),
                ('aspect', models.IntegerField(default=0)),
                ('image', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('title_1', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('title_2', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('text_1', models.TextField(blank=True, default=None, null=True)),
                ('text_2', models.TextField(blank=True, default=None, null=True)),
                ('text_3', models.TextField(blank=True, default=None, null=True)),
                ('text_4', models.TextField(blank=True, default=None, null=True)),
                ('text_5', models.TextField(blank=True, default=None, null=True)),
                ('text_6', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'person_person_aspect_descriptions_male',
            },
        ),
        migrations.CreateModel(
            name='PersonSelfAspectDescriptionFemale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence', models.IntegerField(default=0)),
                ('archetype', models.IntegerField(default=0)),
                ('aspect', models.IntegerField(default=0)),
                ('image', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('title_1', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('title_2', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('text_1', models.TextField(blank=True, default=None, null=True)),
                ('text_2', models.TextField(blank=True, default=None, null=True)),
                ('text_3', models.TextField(blank=True, default=None, null=True)),
                ('text_4', models.TextField(blank=True, default=None, null=True)),
                ('text_5', models.TextField(blank=True, default=None, null=True)),
                ('text_6', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'person_self_aspect_descriptions_female',
            },
        ),
        migrations.CreateModel(
            name='PersonSelfAspectDescriptionMale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence', models.IntegerField(default=0)),
                ('archetype', models.IntegerField(default=0)),
                ('aspect', models.IntegerField(default=0)),
                ('image', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('title_1', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('title_2', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('text_1', models.TextField(blank=True, default=None, null=True)),
                ('text_2', models.TextField(blank=True, default=None, null=True)),
                ('text_3', models.TextField(blank=True, default=None, null=True)),
                ('text_4', models.TextField(blank=True, default=None, null=True)),
                ('text_5', models.TextField(blank=True, default=None, null=True)),
                ('text_6', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'person_self_aspect_descriptions_male',
            },
        ),
        migrations.CreateModel(
            name='SelfPersonAspectDescriptionFemale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence', models.IntegerField(default=0)),
                ('archetype', models.IntegerField(default=0)),
                ('aspect', models.IntegerField(default=0)),
                ('image', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('title_1', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('title_2', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('text_1', models.TextField(blank=True, default=None, null=True)),
                ('text_2', models.TextField(blank=True, default=None, null=True)),
                ('text_3', models.TextField(blank=True, default=None, null=True)),
                ('text_4', models.TextField(blank=True, default=None, null=True)),
                ('text_5', models.TextField(blank=True, default=None, null=True)),
                ('text_6', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'self_person_aspect_descriptions_female',
            },
        ),
        migrations.CreateModel(
            name='SelfPersonAspectDescriptionMale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence', models.IntegerField(default=0)),
                ('archetype', models.IntegerField(default=0)),
                ('aspect', models.IntegerField(default=0)),
                ('image', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('title_1', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('title_2', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('text_1', models.TextField(blank=True, default=None, null=True)),
                ('text_2', models.TextField(blank=True, default=None, null=True)),
                ('text_3', models.TextField(blank=True, default=None, null=True)),
                ('text_4', models.TextField(blank=True, default=None, null=True)),
                ('text_5', models.TextField(blank=True, default=None, null=True)),
                ('text_6', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'self_person_aspect_descriptions_male',
            },
        ),
        migrations.CreateModel(
            name='SelfSelfAspectDescriptionFemale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence', models.IntegerField(default=0)),
                ('archetype', models.IntegerField(default=0)),
                ('aspect', models.IntegerField(default=0)),
                ('image', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('title_1', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('title_2', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('text_1', models.TextField(blank=True, default=None, null=True)),
                ('text_2', models.TextField(blank=True, default=None, null=True)),
                ('text_3', models.TextField(blank=True, default=None, null=True)),
                ('text_4', models.TextField(blank=True, default=None, null=True)),
                ('text_5', models.TextField(blank=True, default=None, null=True)),
                ('text_6', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'self_self_aspect_descriptions_female',
            },
        ),
        migrations.CreateModel(
            name='SelfSelfAspectDescriptionMale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence', models.IntegerField(default=0)),
                ('archetype', models.IntegerField(default=0)),
                ('aspect', models.IntegerField(default=0)),
                ('image', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('title_1', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('title_2', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('text_1', models.TextField(blank=True, default=None, null=True)),
                ('text_2', models.TextField(blank=True, default=None, null=True)),
                ('text_3', models.TextField(blank=True, default=None, null=True)),
                ('text_4', models.TextField(blank=True, default=None, null=True)),
                ('text_5', models.TextField(blank=True, default=None, null=True)),
                ('text_6', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'self_self_aspect_descriptions_male',
            },
        ),
    ]
