# Generated by Django 2.2.7 on 2020-02-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orienters', '0002_personpersonaspectdescriptionfemale_personpersonaspectdescriptionmale_personselfaspectdescriptionfem'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifierShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(default='self', max_length=8)),
                ('report_id', models.IntegerField(default=None)),
                ('entity_type', models.CharField(default='group', max_length=8)),
                ('entity_id', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'identifier_share',
            },
        ),
    ]
