# Generated by Django 2.2.7 on 2020-02-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orienters', '0004_auto_20200207_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportshare',
            old_name='report_type',
            new_name='report_stage',
        ),
    ]
