# Generated by Django 2.2.7 on 2020-02-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orienters', '0005_auto_20200207_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportShare',
        ),
    ]
