# Generated by Django 2.2.7 on 2020-02-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orienters', '0006_delete_reportshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_stage', models.CharField(default='identifier', max_length=16)),
                ('report_target', models.CharField(default='self', max_length=8)),
                ('report_id', models.IntegerField(default=None)),
                ('entity_type', models.CharField(default='group', max_length=8)),
                ('entity_id', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'report_share',
            },
        ),
    ]
