# Generated by Django 2.2.7 on 2020-02-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orienters', '0007_reportshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportshare',
            name='report_target',
            field=models.CharField(default='self', max_length=16),
        ),
    ]
