# Generated by Django 2.2.7 on 2020-02-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orienters', '0008_auto_20200213_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_stage', models.CharField(default='identifier', max_length=16)),
                ('report_target', models.CharField(default='self', max_length=16)),
                ('report_id', models.IntegerField(default=None)),
                ('cadence', models.CharField(default=None, max_length=16)),
                ('index', models.IntegerField(default=None)),
                ('text', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'report_answer',
            },
        ),
    ]
