# Generated by Django 2.2.7 on 2020-02-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orienters', '0009_reportanswer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reportanswer',
            table='report_answers',
        ),
        migrations.AlterModelTable(
            name='reportshare',
            table='report_shares',
        ),
    ]
