# Generated by Django 2.2.7 on 2020-02-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orienters', '0010_auto_20200214_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportanswer',
            old_name='index',
            new_name='iindex',
        ),
    ]
