# Generated by Django 2.2.7 on 2020-02-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orienters', '0011_auto_20200214_1504'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='connector',
            index=models.Index(fields=['user'], name='connectors_user_id_82592c_idx'),
        ),
        migrations.AddIndex(
            model_name='reflector',
            index=models.Index(fields=['user'], name='reflectors_user_id_97d773_idx'),
        ),
        migrations.AddIndex(
            model_name='reportanswer',
            index=models.Index(fields=['report_stage', 'report_target', 'report_id', 'cadence', 'iindex'], name='report_answ_report__c38567_idx'),
        ),
        migrations.AddIndex(
            model_name='reportshare',
            index=models.Index(fields=['report_stage', 'report_target', 'report_id', 'entity_type'], name='report_shar_report__586a88_idx'),
        ),
    ]
