# Generated by Django 2.2.7 on 2020-02-19 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orienters', '0012_auto_20200215_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Echo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='self', max_length=16)),
                ('name', models.CharField(default=None, max_length=64)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('question', models.TextField(default=None)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group')),
            ],
            options={
                'db_table': 'echoes',
            },
        ),
        migrations.CreateModel(
            name='SelfEcho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_01', models.IntegerField(blank=True, default=None, null=True)),
                ('word_02', models.IntegerField(blank=True, default=None, null=True)),
                ('word_03', models.IntegerField(blank=True, default=None, null=True)),
                ('word_04', models.IntegerField(blank=True, default=None, null=True)),
                ('word_05', models.IntegerField(blank=True, default=None, null=True)),
                ('word_06', models.IntegerField(blank=True, default=None, null=True)),
                ('word_07', models.IntegerField(blank=True, default=None, null=True)),
                ('word_08', models.IntegerField(blank=True, default=None, null=True)),
                ('word_09', models.IntegerField(blank=True, default=None, null=True)),
                ('word_10', models.IntegerField(blank=True, default=None, null=True)),
                ('word_11', models.IntegerField(blank=True, default=None, null=True)),
                ('word_12', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('input_count', models.IntegerField(default=0)),
                ('input_keywords', models.CharField(default=None, max_length=256)),
                ('input_data', models.TextField(blank=True, default=None, null=True)),
                ('echo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orienters.Echo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'self_echo',
            },
        ),
        migrations.AddIndex(
            model_name='echo',
            index=models.Index(fields=['group'], name='echoes_group_i_8581ac_idx'),
        ),
        migrations.AddIndex(
            model_name='echo',
            index=models.Index(fields=['type'], name='echoes_type_3e6bad_idx'),
        ),
    ]
